version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - ./datasets:/data
    environment:
      - DB_HOST=db
      - DB_PORT=5433
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=faso
    depends_on:
      - db
    command: ["gunicorn", "-b", "0.0.0.0:5001", "app:app"]

  processor:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./datasets:/data
    environment:
      - DB_HOST=db
      - DB_PORT=5433
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=faso
    depends_on:
      - db
    command: ["python", "data_processor.py"]

  db:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=faso
    volumes:
      - ./db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
